### ISSUE TITLE
Backup not retained when installing over the top of previous install

### ISSUE THREAD

**Issue by brianread108** [fabriziosalmi/proxmox-vm-autoscale#14]
**Describe the bug**
Config.yaml is backed up to installation directory, then the directory is removed.

**To Reproduce**
Install over the top of previous install

**Expected behavior**
Backup is retained

**Comment by fabriziosalmi** [comment]
Tried [this approach](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/1b27eaf346061e10c92300b1b67ff340cd4a0b22), ty to point me out to that newbie error :)
