### ISSUE TITLE
Email not sent when configured in config.yaml

### ISSUE THREAD

**Issue by brianread108** [fabriziosalmi/proxmox-vm-autoscale#15]
**Describe the bug**
I have configured my email server details in the config.yaml, but I still get the error message in the logs:
c 03 19:01:46 pve python3[815037]: WARNING: No notification method is enabled.

**To Reproduce**
1. Configure config.yaml:
# Alerts configuration (Optional)
alerts:
  email_enabled: true
  email_recipient: smeserver@bjsystems.co.uk
  smtp_server: 192.168.1.4
  smtp_port: 465
  smtp_user: smeserver
  smtp_password: xxxxxxxxxxxxxx

2. investigate logs

**Expected behavior**
Error message emailed

**Additional context**

Looking at the python in autoscale.py, it looks to me that it is expecting a yaml entity "smtp" when it is clearly called "alerts".  I may be misunderstanding it?

def send_notification(message, priority=5):
    if config.get('gotify', {}).get('enabled', False):
        send_gotify_notification(message, priority)
    elif config.get('smtp', {}).get('enabled', False):
        send_smtp_notification(message)
    else:
        logger.warning(f"No notification method is enabled. Message: {message}")

**Comment by fabriziosalmi** [comment]
Helo and sorry to broke existing working feature :)

I applied [this approach](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/d6282bdfceeae568a0f138c93438376c4e5b8c13) to fix the issue. TY to point me out to that.
