### ISSUE TITLE
Add option to only scale online VMs

### ISSUE THREAD

**Issue by 13robin37** [fabriziosalmi/proxmox-vm-autoscale#4]
Currently the autoscaler checks offline VMs as well and scales them down which makes them end up with the minimum RAM and CPU configured. Maybe an option to only scale online VMs would be beneficial.

**Comment by fabriziosalmi** [comment]
Prioritized of course! Thank You to point me out to that.

**Comment by fabriziosalmi** [comment]
fixed!
