### ISSUE TITLE
0% CPU 100% RAM usage, does not scale anymnore

### ISSUE THREAD

**Issue by KlopZzz** [fabriziosalmi/proxmox-vm-autoscale#5]
Worked before but then stopped working and showed 0% CPU usage 100% RAM usage even though it is not. Does not scale anymore

![image](https://github.com/user-attachments/assets/26d3fabb-45f0-452e-a2c5-0450ad826f77)
![image](https://github.com/user-attachments/assets/3eaf28ec-90bc-466a-8fc5-d400d3b41050)
![image](https://github.com/user-attachments/assets/b7b680a1-6495-4d73-b440-2e822387ebfc)

`qm status 101 --verbose`

![image](https://github.com/user-attachments/assets/733e0da0-23a2-4cf0-b907-388fc5d9a937)

**Comment by fabriziosalmi** [comment]
Maybe it will be easy to fix, just by accounting for such cases. I will hopefully provide a fix tonite!
Thank You to point me out to this

**Comment by fabriziosalmi** [comment]
Fixed [here](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/b95844625681e191212284db12f8987e6664fc94) 🍻
