### ISSUE TITLE
VM will not boot with IOMMU for nvidia GPU on Ubuntu 22.04

### ISSUE THREAD

**Issue by burnbrigther** [fabriziosalmi/proxmox-vm-autoscale#6]
RAM: 32GB (reduced to 2048)
NUMA enabled
Hotplug CPU/Mem enabled
Added for CPU:
/lib/udev/rules.d/80-hotplug-cpu.rules
SUBSYSTEM=="cpu", ACTION=="add", TEST=="online", ATTR{online}=="0", ATTR{online}="1"
According to documentation, nothing else needs to be added for hot memory.
Seeing this on boot up of the VM:
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm: VFIO_MAP_DMA failed: Invalid argument`
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm: vfio_container_dma_map(0x5ae448831540, 0x3ffc00000000, 0x400000000, 0x706d10000000) = -22 (Invalid argument) `
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm: VFIO_MAP_DMA failed: Invalid argument `
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm: vfio_container_dma_map(0x5ae448831540, 0x400000000000, 0x2000000, 0x70715e000000) = -22 (Invalid argument) `
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm: kvm_set_user_memory_region: KVM_SET_USER_MEMORY_REGION failed, slot=10, start=0x400000000000, size=0x2000000: Invalid argument `
`Oct 01 08:04:49 myhost QEMU[1019150]: kvm_set_phys_mem: error registering slot: Invalid argument`

For IOMMU to work, you must add a PCI device
![image](https://github.com/user-attachments/assets/c69b8cf3-cfcd-4df8-a90e-3df4433450a1)
If you remove this device, the VM boots just fine and the above errors go away.

**Comment by fabriziosalmi** [comment]
should be fixed [here](https://github.com/fabriziosalmi/proxmox-vm-autoscale/commit/40b955b1bb23607fdcdc9722645702d534c6b014), can you confirm?
